// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at http://mozilla.org/MPL/2.0/.

//! The test benches of the VUnit VHDL libraries (`vunit/vhdl/*/test`), with each `run.py`
//! translated into a [`ProjectSpec`].
//!
//! Left out, because the frontend doesn't support what they need (see `UPSTREAM.md`):
//!
//! - `check/test/tb_check_relation*.vhd`: the check preprocessor;
//! - `check/test/tb_check_equal.vhd` and `tb_check_match.vhd`: generated by Python tools in
//!   `run.py`, not checked in;
//! - `com/test/tb_com_codec.vhd`: com codec generation;
//! - `logging/test/tb_location.vhd`: the location preprocessor;
//! - the `Test random` configurations of `tb_sim_time_formatting`, which `run.py` draws with
//!   Python's random generator; one fixed configuration replaces them.
//!
//! AI NOTICE: Generated, minimally reviewed.

use risim_vunit_frontend::Runtime;
use risim_vunit_frontend::SimulatorKind;
use risim_vunit_frontend::pattern::Pattern;
use risim_vunit_frontend::spec::ConfigurationSpec;
use risim_vunit_frontend::spec::Feature;
use risim_vunit_frontend::spec::ProjectSpec;
use risim_vunit_frontend::spec::TestConfigSpec;

use crate::harness;
use crate::harness::RisimDeviations;
use crate::harness::Root;
use crate::harness::config;
use crate::harness::generics;
use crate::harness::target;

/// Runs all testcases of `spec`; the testcases in `failing` must fail and all others pass,
/// changed by `risim` on the `risim` backend.
async fn check(
    simulator: SimulatorKind,
    runtime: &Runtime,
    root: &Root,
    spec: &ProjectSpec,
    failing: &[&str],
    risim: RisimDeviations,
) {
    let outcome = harness::simulate_all(runtime, &root.path, spec, simulator).await;
    outcome.assert_all_pass_except(failing, risim);
}

/// The test files of library `name` (`vunit/vhdl/<name>/test`).
fn test_files(name: &str, skip: impl Fn(&str) -> bool) -> Vec<String> {
    harness::vhd_files(&harness::vhdl_dir().join(name).join("test"), skip)
}

/// A configuration with generics.
fn config_with(name: &str, pairs: &[(&str, &str)]) -> ConfigurationSpec {
    ConfigurationSpec {
        generics: generics(pairs),
        ..config(name)
    }
}

/// Configurations of `target`.
fn configs_of(target_name: &str, configurations: Vec<ConfigurationSpec>) -> TestConfigSpec {
    TestConfigSpec {
        configurations,
        ..target(target_name)
    }
}

pub async fn check_lib(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    let logging_support = harness::vhdl_dir().join("logging/test/test_support_pkg.vhd");
    // Old copies of the generated testbenches may still be around; they're gitignored.
    spec.add_library(
        "lib",
        test_files("check", |name| {
            name.starts_with("tb_check_relation")
                || name == "tb_check_equal.vhd"
                || name == "tb_check_match.vhd"
        }),
    )
    .add_library("logging_tb_lib", [logging_support.to_string()]);
    spec.test_configs.push(configs_of(
        "lib.tb_check",
        vec![
            config_with("using check", &[("use_check_not_check_true", "True")]),
            config_with("using check_true", &[("use_check_not_check_true", "False")]),
        ],
    ));
    // risim: association, enclosing unit, access.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        CHECK_FAILURES,
        RisimDeviations::AllFailing,
    )
    .await;
}

/// Tests of `run_all_in_same_sim` testbenches that rely on the earlier tests of the same
/// simulation. They pass when all tests of the testbench run in one simulation.
const CHECK_FAILURES: &[&str] = &[
    "lib.tb_check_false.Test should pass on false and logic 0 inputs to sequential checks",
    "lib.tb_check_next.Test should fail when expr is false num_cks enabled cycles after \
     start_event",
    "lib.tb_check_next.Test should handle a mix of passing and failing overlapping checks when \
     allowed",
];

pub async fn com(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    spec.add_library(
        "tb_com_lib",
        test_files("com", |name| name == "tb_com_codec.vhd"),
    );
    // risim: enclosing unit, image, physical.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        &[],
        RisimDeviations::AllFailing,
    )
    .await;
}

pub async fn data_types(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    let mut files = vec![
        harness::vhdl_dir()
            .join("logging/test/test_support_pkg.vhd")
            .to_string(),
    ];
    files.extend(test_files("data_types", |_| false));
    spec.add_library("vunit_lib", files);
    // risim: access, enclosing unit, image, physical.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        &[],
        RisimDeviations::AllFailing,
    )
    .await;
}

pub async fn dictionary(simulator: SimulatorKind) {
    // risim: enclosing unit.
    simple_library(simulator, "dictionary", "lib", RisimDeviations::AllFailing).await;
}

pub async fn path(simulator: SimulatorKind) {
    // risim: enclosing unit.
    simple_library(simulator, "path", "lib", RisimDeviations::AllFailing).await;
}

pub async fn run(simulator: SimulatorKind) {
    // risim: image.
    simple_library(simulator, "run", "tb_run_lib", RisimDeviations::AllFailing).await;
}

pub async fn string_ops(simulator: SimulatorKind) {
    // risim: access.
    simple_library(simulator, "string_ops", "lib", RisimDeviations::AllFailing).await;
}

/// `UI.add_library(library).add_source_files(ROOT / "test" / "*.vhd")`.
async fn simple_library(
    simulator: SimulatorKind,
    name: &str,
    library: &str,
    risim: RisimDeviations,
) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    spec.add_library(library, test_files(name, |_| false));
    check(simulator, &runtime, &root, &spec, &[], risim).await;
}

pub async fn random(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    spec.add_feature(Feature::Random)
        .add_library("vunit_lib", test_files("random", |_| false));
    // risim: image.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        &[],
        RisimDeviations::AllFailing,
    )
    .await;
}

// -------------------------------------------------------------------------------------------------
// logging
// -------------------------------------------------------------------------------------------------

pub async fn logging(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    spec.add_library(
        "vunit_lib",
        test_files("logging", |name| name == "tb_location.vhd"),
    );
    let tb = "vunit_lib.tb_sim_time_formatting";
    spec.test_configs.push(TestConfigSpec {
        generics: generics(&[("n_performance_iterations", "1")]),
        ..target(tb)
    });
    let mut tests: Vec<(&str, Vec<ConfigurationSpec>)> = Vec::new();
    for (test, cfg_name, test_time, scaling, n_decimals) in sim_time_vectors() {
        let (auto_scaling, expected) = expected_time(test_time, scaling, n_decimals);
        let configuration = config_with(
            &cfg_name,
            &[
                ("test_time", &test_time.to_string()),
                ("scaling", &scaling.to_string()),
                ("n_decimals", &n_decimals.to_string()),
                ("expected", &expected),
                ("auto_scaling", &auto_scaling.to_string()),
            ],
        );
        match tests.iter_mut().find(|(name, _)| *name == test) {
            Some((_, configurations)) => configurations.push(configuration),
            None => tests.push((test, vec![configuration])),
        }
    }
    for (test, configurations) in tests {
        spec.test_configs
            .push(configs_of(&format!("{tb}.{test}"), configurations));
    }
    // risim: image, access.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        &[],
        RisimDeviations::AllFailing,
    )
    .await;
}

const NATIVE_UNIT_SCALING: i64 = 0;
const AUTO_UNIT_SCALING: i64 = -1;
const FULL_RESOLUTION: i64 = -1;

/// The test vectors of `logging/run.py`: test, configuration, time, scaling and decimals.
#[expect(clippy::too_many_lines, reason = "follows run.py")]
fn sim_time_vectors() -> Vec<(&'static str, String, u64, i64, i64)> {
    let mut vectors = Vec::new();
    let mut add = |test: &'static str, name: String, time: u64, scaling: i64, decimals: i64| {
        vectors.push((test, name, time, scaling, decimals));
    };

    add(
        "Test native unit",
        "no_decimals".to_owned(),
        123_456,
        NATIVE_UNIT_SCALING,
        0,
    );
    for scaling in [1, 1000, 1_000_000, 1_000_000_000] {
        add(
            "Test units of differents scales wrt the resolution_limit",
            format!("scaling={scaling}"),
            123_456,
            scaling,
            0,
        );
    }
    let auto = "Test auto unit";
    add(
        auto,
        "three_integer_digits".to_owned(),
        456_789,
        AUTO_UNIT_SCALING,
        0,
    );
    add(
        auto,
        "two_integer_digits".to_owned(),
        56_789,
        AUTO_UNIT_SCALING,
        0,
    );
    add(
        auto,
        "one_integer_digit".to_owned(),
        6_789,
        AUTO_UNIT_SCALING,
        0,
    );
    let limiting = "Test limiting number of decimals";
    for n_decimals in 0..3 {
        for scaling in [1, 1000, 1_000_000] {
            add(
                limiting,
                format!("n_decimals={n_decimals}_scaling={scaling}"),
                456_789,
                scaling,
                n_decimals,
            );
        }
        add(
            limiting,
            format!("n_decimals={n_decimals}_native_unit"),
            456_789,
            NATIVE_UNIT_SCALING,
            n_decimals,
        );
        add(
            limiting,
            format!("n_decimals={n_decimals}_auto_unit"),
            456_789,
            AUTO_UNIT_SCALING,
            n_decimals,
        );
    }
    add(
        limiting,
        "no significant digits among decimals".to_owned(),
        456_789,
        1_000_000_000,
        3,
    );
    add(
        limiting,
        "some significant digits among decimals".to_owned(),
        456_789,
        1_000_000_000,
        4,
    );
    let full = "Test full resolution";
    for scaling in [1, 1000, 1_000_000, 1_000_000_000] {
        add(
            full,
            format!("scaling={scaling}"),
            123_456,
            scaling,
            FULL_RESOLUTION,
        );
    }
    add(
        full,
        "native_unit".to_owned(),
        123_456,
        NATIVE_UNIT_SCALING,
        FULL_RESOLUTION,
    );
    add(
        full,
        "auto_unit".to_owned(),
        123_456,
        AUTO_UNIT_SCALING,
        FULL_RESOLUTION,
    );
    // `round(123456, -n)` for n = 1..6.
    for (n_zeros, time) in [
        (1, 123_460),
        (2, 123_500),
        (3, 123_000),
        (4, 120_000),
        (5, 100_000),
        (6, 0),
    ] {
        add(
            "Test trailing zeros",
            format!("n_zeros={n_zeros}"),
            time,
            1000,
            3,
        );
    }
    let zero = "Test zero";
    add(
        zero,
        "auto_with_all_decimals".to_owned(),
        0,
        AUTO_UNIT_SCALING,
        FULL_RESOLUTION,
    );
    add(zero, "scaling_with_fix_decimals".to_owned(), 0, 1000, 2);
    add(zero, "scaling_with_no_decimals".to_owned(), 0, 1000, 0);
    // Instead of the configurations that `run.py` draws at random.
    // 2**31 - 1
    let time = 0x7FFF_FFFF;
    add(
        "Test random",
        format!("{time}_{AUTO_UNIT_SCALING}_5"),
        time,
        AUTO_UNIT_SCALING,
        5,
    );
    vectors
}

/// `calculate_generics` of `logging/run.py`: the auto scaling and the expected text.
fn expected_time(test_time: u64, scaling: i64, n_decimals: i64) -> (i64, String) {
    // The number of decimal digits minus one, `floor(log10(value))`.
    let log10 = |value: u64| value.ilog10();
    let auto_scaling = if test_time == 0 || scaling != AUTO_UNIT_SCALING {
        1
    } else {
        10_i64.pow(log10(test_time) / 3 * 3)
    };
    let resolved_scaling = match scaling {
        1.. => scaling,
        NATIVE_UNIT_SCALING => 1,
        _ => auto_scaling,
    };

    let mut digits = test_time.to_string();
    let n_to_use = log10(u64::try_from(resolved_scaling).expect("positive")) as usize;
    if n_to_use >= digits.len() {
        digits = format!("{}{digits}", "0".repeat(n_to_use - digits.len() + 1));
    }
    let split = digits.len() - n_to_use;
    let (integer, fraction) = digits.split_at(split);
    let expected = if n_to_use == 0 {
        match usize::try_from(n_decimals) {
            Ok(decimals @ 1..) => format!("{integer}.{}", "0".repeat(decimals)),
            _ => integer.to_owned(),
        }
    } else {
        match usize::try_from(n_decimals) {
            Ok(0) => integer.to_owned(),
            Err(_) => format!("{integer}.{fraction}"),
            Ok(decimals) if decimals <= n_to_use => {
                format!(
                    "{integer}.{}",
                    fraction.get(..decimals).expect("ASCII digits")
                )
            },
            Ok(decimals) => format!("{integer}.{fraction}{}", "0".repeat(decimals - n_to_use)),
        }
    };
    (auto_scaling, expected)
}

// -------------------------------------------------------------------------------------------------
// verification_components
// -------------------------------------------------------------------------------------------------

#[expect(clippy::too_many_lines, reason = "follows run.py")]
pub async fn verification_components(simulator: SimulatorKind) {
    let runtime = harness::runtime().await;
    let root = Root::new();
    let mut spec = ProjectSpec::new();
    spec.add_feature(Feature::Random)
        .add_feature(Feature::VerificationComponents)
        .add_library(
            "vunit_lib",
            test_files("verification_components", |_| false),
        );
    let names = harness::testcase_names(&runtime, &root.path, &spec).await;
    let tests = |tb: &str| harness::tests_of(&names, &format!("vunit_lib.{tb}"));
    let configs = &mut spec.test_configs;
    let mut add = |tb: &str, test: &str, configurations: Vec<ConfigurationSpec>| {
        configs.push(configs_of(
            &format!("vunit_lib.{tb}.{test}"),
            configurations,
        ));
    };

    for test in tests("tb_avalon_slave") {
        let configurations = tb_cfg_configs(
            &[
                ("data_width", &["32"]),
                ("num_cycles", &["1", "2", "64"]),
                ("readdatavalid_prob", &["1.0", "0.3"]),
                ("waitrequest_prob", &["0.0", "0.4"]),
            ],
            &[
                "data_width",
                "readdatavalid_prob",
                "waitrequest_prob",
                "num_cycles",
            ],
        );
        add("tb_avalon_slave", test, configurations);
    }

    for test in tests("tb_avalon_master") {
        let order = [
            "readdatavalid_prob",
            "waitrequest_prob",
            "write_prob",
            "read_prob",
            "transfers",
        ];
        let configurations = if test == "wr single rd single" {
            tb_cfg_configs(
                &[
                    ("transfers", &["1"]),
                    ("readdatavalid_prob", &["1.0"]),
                    ("waitrequest_prob", &["0.0"]),
                    ("write_prob", &["1.0"]),
                    ("read_prob", &["1.0"]),
                ],
                &order,
            )
        } else {
            tb_cfg_configs(
                &[
                    ("transfers", &["64"]),
                    ("readdatavalid_prob", &["1.0", "0.3"]),
                    ("waitrequest_prob", &["0.0", "0.7"]),
                    ("write_prob", &["1.0", "0.3"]),
                    ("read_prob", &["1.0", "0.3"]),
                ],
                &order,
            )
        };
        add("tb_avalon_master", test, configurations);
    }

    for test in tests("tb_wishbone_slave") {
        let configurations = wishbone_configs(
            &["8", "32"],
            &["1", "64"],
            &["1.0"],
            &["0.3", "1.0"],
            &["0.4", "0.0"],
            &["True"],
        );
        add("tb_wishbone_slave", test, configurations);
    }

    for test in tests("tb_wishbone_master") {
        let configurations = if test == "slave comb ack" {
            wishbone_configs(&["32"], &["64"], &["1.0"], &["1.0"], &["0.0"], &["False"])
        } else {
            wishbone_configs(
                &["8", "32"],
                &["1", "64"],
                &["0.3", "1.0"],
                &["0.3", "1.0"],
                &["0.4", "0.0"],
                &["True"],
            )
        };
        add("tb_wishbone_master", test, configurations);
    }

    let check_pattern = Pattern::new("*check");
    for test in tests("tb_axi_stream") {
        if !check_pattern.matches(test) {
            continue;
        }
        let mut configurations = Vec::new();
        for id in ["0", "8"] {
            for dest in ["0", "8"] {
                for user in ["0", "8"] {
                    for data in ["8", "16"] {
                        configurations.push(config_with(
                            &format!("id_l={id} dest_l={dest} user_l={user} data_l={data}"),
                            &[
                                ("g_data_length", data),
                                ("g_id_length", id),
                                ("g_dest_length", dest),
                                ("g_user_length", user),
                            ],
                        ));
                    }
                }
            }
        }
        add("tb_axi_stream", test, configurations);
    }
    let no_tkeep = TestConfigSpec {
        generics: generics(&[("g_data_length", "16")]),
        ..target("vunit_lib.tb_axi_stream.test passing with no tkeep")
    };

    let checker = "tb_axi_stream_protocol_checker";
    let tdata = Pattern::new("*passing*tdata*");
    let tid_width = Pattern::new("*failing*tid width*");
    for test in tests(checker) {
        if tdata.matches(test) {
            let configurations = ["0", "8", "32"]
                .into_iter()
                .map(|length| {
                    config_with(&format!("data_length={length}"), &[("data_length", length)])
                })
                .collect();
            add(checker, test, configurations);
        } else if tid_width.matches(test) {
            add(
                checker,
                test,
                vec![
                    config_with("dest_length=25", &[("dest_length", "25")]),
                    config_with(
                        "id_length=8 dest_length=17",
                        &[("id_length", "8"), ("dest_length", "17")],
                    ),
                ],
            );
        }
    }
    add(
        checker,
        "Test failing check of that tready comes within max_waits after valid",
        ["0", "8"]
            .into_iter()
            .map(|waits| config_with(&format!("max_waits={waits}"), &[("max_waits", waits)]))
            .collect(),
    );
    configs.push(no_tkeep);

    // risim: enclosing unit, image, access, driver.
    check(
        simulator,
        &runtime,
        &root,
        &spec,
        &[],
        RisimDeviations::AllFailing,
    )
    .await;
}

/// `gen_wb_tests` of `verification_components/run.py`.
fn wishbone_configs(
    dat_width: &[&str],
    num_cycles: &[&str],
    strobe_prob: &[&str],
    ack_prob: &[&str],
    stall_prob: &[&str],
    slave_inst: &[&str],
) -> Vec<ConfigurationSpec> {
    tb_cfg_configs(
        &[
            ("dat_width", dat_width),
            ("num_cycles", num_cycles),
            ("strobe_prob", strobe_prob),
            ("ack_prob", ack_prob),
            ("stall_prob", stall_prob),
            ("slave_inst", slave_inst),
            ("adr_width", &["32"]),
        ],
        &[
            "dat_width",
            "adr_width",
            "strobe_prob",
            "ack_prob",
            "stall_prob",
            "num_cycles",
            "slave_inst",
        ],
    )
}

/// One configuration per combination of `values` (in `itertools.product` order), named after
/// and with the generic `encoded_tb_cfg` set to `key:value` pairs in `order`, joined by commas.
fn tb_cfg_configs(values: &[(&str, &[&str])], order: &[&str]) -> Vec<ConfigurationSpec> {
    let mut combinations: Vec<Vec<(&str, &str)>> = vec![Vec::new()];
    for &(key, choices) in values {
        combinations = combinations
            .into_iter()
            .flat_map(|combination| {
                choices.iter().map(move |&choice| {
                    let mut extended = combination.clone();
                    extended.push((key, choice));
                    extended
                })
            })
            .collect();
    }
    combinations
        .into_iter()
        .map(|combination| {
            let encoded = order
                .iter()
                .map(|key| {
                    let (_, value) = combination
                        .iter()
                        .find(|(name, _)| name == key)
                        .expect("every key has a value");
                    format!("{key}:{value}")
                })
                .collect::<Vec<_>>()
                .join(",");
            config_with(&encoded, &[("encoded_tb_cfg", &encoded)])
        })
        .collect()
}
